### ISSUE TITLE
Bug: Empty deflayer causes formatter crash

### ISSUE THREAD

**Issue by rszyma** [rszyma/vscode-kanata#33]
```
panicked at src/formatter/defsrc_layout/mod.rs:47:16:
attempt to subtract with overflow

Stack:

Error
    at /home/n/.vscode/extensions/rszyma.vscode-kanata-0.11.21/out/server.js:37:2918
    at X (/home/n/.vscode/extensions/rszyma.vscode-kanata-0.11.21/out/server.js:34:424)
    at S.exports.__wbg_new_abda76e883ba8a5f (/home/n/.vscode/extensions/rszyma.vscode-kanata-0.11.21/out/server.js:37:2899)
    at kls.wasm.console_error_panic_hook::Error::new::ha842e8090e6bbecd (wasm://wasm/kls.wasm-01bd220a:wasm-function[11743]:0x4e4ab6)
    at kls.wasm.console_error_panic_hook::hook_impl::h49cd7ab8835e94ec (wasm://wasm/kls.wasm-01bd220a:wasm-function[2663]:0x366209)
    at kls.wasm.console_error_panic_hook::hook::h1cdcb3fd683dbf05 (wasm://wasm/kls.wasm-01bd220a:wasm-function[14432]:0x50cfcd)
    at kls.wasm.core::ops::function::Fn::call::h63f1386438e14437 (wasm://wasm/kls.wasm-01bd220a:wasm-function[12283]:0x4ee0fb)
    at kls.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/kls.wasm-01bd220a:wasm-function[4928]:0x409d4c)
    at kls.wasm.std::panicking::begin_panic_handler::{{closure}}::hd496964d114e98b9 (wasm://wasm/kls.wasm-01bd220a:wasm-function[6788]:0x4602b5)
    at kls.wasm.std::sys_common::backtrace::__rust_end_short_backtrace::h0d4686a7fe3981a4 (wasm://wasm/kls.wasm-01bd220a:wasm-function[16251]:0x51df41)


[Error - 5:29:31 PM] Request textDocument/formatting failed.
```

Reproductible with config:

```
(deflayer )
```

**Comment by rszyma** [comment]
it was fixed in d1f5fea a while ago
